// Idiom database for the learning-oriented game.
// Each entry:
//  w   : the idiom (4 Chinese characters)
//  p   : full pinyin with tone marks
//  pw  : per-character pinyin array (for the breakdown card)
//  e   : emoji hint (literal image)
//  lit : English literal translation (what the characters say)
//  en  : English figurative meaning (what the idiom means)
//  lvl : difficulty 1 = common, 2 = intermediate, 3 = advanced/literary
const IDIOMS = [
  // ---- Level 1: common ----
  {w:"画蛇添足", p:"huà shé tiān zú", pw:["huà","shé","tiān","zú"], e:"🐍➕🦶",
   lit:"draw a snake and add feet to it",
   en:"to ruin a finished thing by adding unnecessary detail",
   lvl:1},
  {w:"守株待兔", p:"shǒu zhū dài tù", pw:["shǒu","zhū","dài","tù"], e:"🌳🐰",
   lit:"guard a tree stump and wait for a rabbit",
   en:"to wait idly for a stroke of luck instead of acting",
   lvl:1},
  {w:"亡羊补牢", p:"wáng yáng bǔ láo", pw:["wáng","yáng","bǔ","láo"], e:"🐑🔧🏠",
   lit:"after a sheep is lost, mend the pen",
   en:"better late than never — fix the problem before more is lost",
   lvl:1},
  {w:"掩耳盗铃", p:"yǎn ěr dào líng", pw:["yǎn","ěr","dào","líng"], e:"🙉🔔",
   lit:"cover your ears while stealing a bell",
   en:"self-deception; fooling yourself that others won't notice",
   lvl:1},
  {w:"狐假虎威", p:"hú jià hǔ wēi", pw:["hú","jià","hǔ","wēi"], e:"🦊👑🐯",
   lit:"a fox borrows the tiger's ferocity",
   en:"to bully people by borrowing someone powerful's authority",
   lvl:1},
  {w:"对牛弹琴", p:"duì niú tán qín", pw:["duì","niú","tán","qín"], e:"🎸🐂",
   lit:"play the lute to a cow",
   en:"to say things to someone who can't or won't understand",
   lvl:1},
  {w:"井底之蛙", p:"jǐng dǐ zhī wā", pw:["jǐng","dǐ","zhī","wā"], e:"🐸🕳️",
   lit:"a frog at the bottom of a well",
   en:"a person with a narrow, limited view of the world",
   lvl:1},
  {w:"画龙点睛", p:"huà lóng diǎn jīng", pw:["huà","lóng","diǎn","jīng"], e:"🐲👁️✨",
   lit:"draw a dragon and dot in its eyes",
   en:"the finishing touch that brings a work to life",
   lvl:1},
  {w:"刻舟求剑", p:"kè zhōu qiú jiàn", pw:["kè","zhōu","qiú","jiàn"], e:"🗡️🚢",
   lit:"mark the boat to find a dropped sword",
   en:"to stick to old methods that no longer fit the situation",
   lvl:1},
  {w:"拔苗助长", p:"bá miáo zhù zhǎng", pw:["bá","miáo","zhù","zhǎng"], e:"🌱⬆️🌾",
   lit:"pull up seedlings to help them grow",
   en:"to spoil a thing by rushing it; over-eagerness backfires",
   lvl:1},
  {w:"杯水车薪", p:"bēi shuǐ chē xīn", pw:["bēi","shuǐ","chē","xīn"], e:"🥤🔥🪵",
   lit:"a cup of water on a cart of firewood",
   en:"a measly effort against a huge problem; totally inadequate",
   lvl:1},
  {w:"火上浇油", p:"huǒ shàng jiāo yóu", pw:["huǒ","shàng","jiāo","yóu"], e:"🔥🛢️",
   lit:"pour oil on a fire",
   en:"to make a bad situation even worse",
   lvl:1},
  {w:"雪中送炭", p:"xuě zhōng sòng tàn", pw:["xuě","zhōng","sòng","tàn"], e:"❄️🪵🔥",
   lit:"send coal in the snow",
   en:"to help someone exactly when they need it most",
   lvl:1},
  {w:"锦上添花", p:"jǐn shàng tiān huā", pw:["jǐn","shàng","tiān","huā"], e:"🌸🎀",
   lit:"add flowers onto brocade",
   en:"to make something already good even better",
   lvl:1},
  {w:"自相矛盾", p:"zì xiāng máo dùn", pw:["zì","xiāng","máo","dùn"], e:"🗡️🛡️",
   lit:"one's own spear against one's own shield",
   en:"self-contradictory",
   lvl:1},
  {w:"一箭双雕", p:"yī jiàn shuāng diāo", pw:["yī","jiàn","shuāng","diāo"], e:"🏹🦅🦅",
   lit:"two eagles with one arrow",
   en:"to achieve two goals with a single effort",
   lvl:1},
  {w:"鸡飞狗跳", p:"jī fēi gǒu tiào", pw:["jī","fēi","gǒu","tiào"], e:"🐔✈️🐶",
   lit:"chickens fly and dogs jump",
   en:"total chaos and commotion",
   lvl:1},
  {w:"狼吞虎咽", p:"láng tūn hǔ yàn", pw:["láng","tūn","hǔ","yàn"], e:"🐺🍚🐯",
   lit:"gulp like a wolf, swallow like a tiger",
   en:"to eat greedily and in a great hurry",
   lvl:1},
  {w:"鹤立鸡群", p:"hè lì jī qún", pw:["hè","lì","jī","qún"], e:"🦢🐔🐔",
   lit:"a crane standing among chickens",
   en:"to stand out, far above the people around you",
   lvl:1},
  {w:"打草惊蛇", p:"dǎ cǎo jīng shé", pw:["dǎ","cǎo","jīng","shé"], e:"🌾🐍",
   lit:"beat the grass and startle the snake",
   en:"to accidentally alert the very person you're after",
   lvl:1},

  // ---- Level 2: intermediate ----
  {w:"望梅止渴", p:"wàng méi zhǐ kě", pw:["wàng","méi","zhǐ","kě"], e:"🟢🟢💧",
   lit:"gaze at plums to quench your thirst",
   en:"to console yourself with imagined satisfaction",
   lvl:2},
  {w:"胸有成竹", p:"xiōng yǒu chéng zhú", pw:["xiōng","yǒu","chéng","zhú"], e:"🎋💚",
   lit:"have a full-grown bamboo in your chest",
   en:"to have a clear, well-thought-out plan before acting",
   lvl:2},
  {w:"愚公移山", p:"yú gōng yí shān", pw:["yú","gōng","yí","shān"], e:"⛰️⛏️",
   lit:"the foolish old man moves a mountain",
   en:"perseverance overcomes impossible-seeming obstacles",
   lvl:2},
  {w:"画饼充饥", p:"huà bǐng chōng jī", pw:["huà","bǐng","chōng","jī"], e:"🥞👀",
   lit:"draw a flatbread to stave off hunger",
   en:"to feed on fantasy instead of solving the real problem",
   lvl:2},
  {w:"指鹿为马", p:"zhǐ lù wéi mǎ", pw:["zhǐ","lù","wéi","mǎ"], e:"👆🦌➡️🐎",
   lit:"point at a deer and call it a horse",
   en:"to deliberately pass off a lie as the truth",
   lvl:2},
  {w:"纸上谈兵", p:"zhǐ shàng tán bīng", pw:["zhǐ","shàng","tán","bīng"], e:"📄⚔️",
   lit:"discussing warfare on paper",
   en:"empty theory with no grounding in reality",
   lvl:2},
  {w:"闻鸡起舞", p:"wén jī qǐ wǔ", pw:["wén","jī","qǐ","wǔ"], e:"🐔🌅💃",
   lit:"rise and dance when the rooster crows",
   en:"to be diligent and driven; to train hard for one's goals",
   lvl:2},
  {w:"顺手牵羊", p:"shùn shǒu qiān yáng", pw:["shùn","shǒu","qiān","yáng"], e:"✋🐑",
   lit:"lead a sheep away along the way",
   en:"to swipe something casually when the chance arises",
   lvl:2},
  {w:"落井下石", p:"luò jǐng xià shí", pw:["luò","jǐng","xià","shí"], e:"🕳️🪨",
   lit:"drop stones down the well on someone",
   en:"to make things worse for a person already in trouble",
   lvl:2},
  {w:"声东击西", p:"shēng dōng jī xī", pw:["shēng","dōng","jī","xī"], e:"🔊东💥西",
   lit:"noise in the east, strike in the west",
   en:"to feint one way while attacking another",
   lvl:2},
  {w:"老马识途", p:"lǎo mǎ shí tú", pw:["lǎo","mǎ","shí","tú"], e:"🐴🛣️",
   lit:"an old horse knows the road",
   en:"experience is a reliable guide",
   lvl:2},
  {w:"草木皆兵", p:"cǎo mù jiē bīng", pw:["cǎo","mù","jiē","bīng"], e:"🌿👥",
   lit:"every bush and tree seems to be a soldier",
   en:"extreme paranoia in a crisis; seeing enemies everywhere",
   lvl:2},

  // ---- Level 3: advanced / literary ----
  {w:"叶公好龙", p:"yè gōng hào lóng", pw:["yè","gōng","hào","lóng"], e:"🐉😍",
   lit:"Lord Ye claims to love dragons",
   en:"professed love that turns to fear when the real thing appears",
   lvl:3},
  {w:"破釜沉舟", p:"pò fǔ chén zhōu", pw:["pò","fǔ","chén","zhōu"], e:"💥🍳⛵",
   lit:"smash the cauldrons and sink the boats",
   en:"to cut off all retreat; an all-or-nothing commitment",
   lvl:3},
  {w:"卧薪尝胆", p:"wò xīn cháng dǎn", pw:["wò","xīn","cháng","dǎn"], e:"🛏️🗡️👅",
   lit:"sleep on brushwood and taste gall",
   en:"to endure bitter hardship to fuel a comeback",
   lvl:3},
  {w:"完璧归赵", p:"wán bì guī zhào", pw:["wán","bì","guī","zhào"], e:"💎🔙",
   lit:"return the jade disc intact to the state of Zhao",
   en:"to return something borrowed in perfect condition",
   lvl:3},
  {w:"四面楚歌", p:"sì miàn chǔ gē", pw:["sì","miàn","chǔ","gē"], e:"🎵四面",
   lit:"surrounded by the songs of Chu",
   en:"isolated and under attack from all sides",
   lvl:3},
  {w:"塞翁失马", p:"sài wēng shī mǎ", pw:["sài","wēng","shī","mǎ"], e:"🐴🏃",
   lit:"the old man of the frontier loses his horse",
   en:"a setback that may turn out to be a blessing in disguise",
   lvl:3},
  {w:"鹬蚌相争", p:"yù bàng xiāng zhēng", pw:["yù","bàng","xiāng","zhēng"], e:"🐦🐚",
   lit:"a snipe and a clam struggle with each other",
   en:"when two rivals fight, a third party reaps the benefit",
   lvl:3},
  {w:"螳螂捕蝉", p:"táng láng bǔ chán", pw:["táng","láng","bǔ","chán"], e:"🦗🦟",
   lit:"the mantis stalks the cicada",
   en:"so fixated on a gain that you miss the danger closing in",
   lvl:3},
  {w:"夸父追日", p:"kuā fù zhuī rì", pw:["kuā","fù","zhuī","rì"], e:"🏃☀️",
   lit:"Kuafu chases the sun",
   en:"to chase an impossible, larger-than-life ambition",
   lvl:3},
  {w:"精卫填海", p:"jīng wèi tián hǎi", pw:["jīng","wèi","tián","hǎi"], e:"🐦🌊🪨",
   lit:"Jingwei tries to fill up the sea",
   en:"dogged, unwavering determination against impossible odds",
   lvl:3}
];

if (typeof window !== "undefined") window.IDIOMS = IDIOMS;
if (typeof module !== "undefined") module.exports = IDIOMS;
